// GENERATED by `yarn workspace @axion/portal-codegen migrate`.
// Translations are carried over from the previous portals where the key matches;
// edit the JSON files to fill the gaps.
import type { LanguageCode, TranslationCatalogue } from '@axion/portal-core';

import ca from './ca.json';
import en from './en.json';
import es from './es.json';
import eu from './eu.json';
import it from './it.json';

export const catalogues: Partial<Record<LanguageCode, TranslationCatalogue>> = {
  en,
  es,
  ca,
  eu,
  it,
};
