/**
 * Convenience re-exports of the generated user-API types.
 *
 * Generated by `yarn codegen` from `web/rest/user/public/apiSpec.json` — do not
 * hand-write these shapes.
 */
export {
  apiBasePath,
  appName,
  fieldsByDefinition,
  resources,
} from '@axion/portal-core/api/generated/user';
export type {
  CallForwardSetting,
  CallForwardSettingDetailed,
  CallStats,
  Country,
  Dashboard,
  FaxesInOut,
  LastMonthCalls,
  Recording,
  UsersCdr,
  UsersCdrCollection,
  UserStatus,
  VoicemailMessageCollection,
} from '@axion/portal-core/api/generated/user/schemas';
