#!/usr/bin/env node
/**
 * Generates src/components/Redesign/icons.css in the four portals.
 *
 * The portals and ivoz-ui draw Material icons (@mui/icons-material). Each of
 * those renders <svg data-testid="<Name>Icon">. icons.css paints a Lucide
 * line icon (ISC licence) over every mapped one with a CSS mask, so the whole
 * UI gets one consistent icon set without touching ivoz-ui or the entity
 * files. Icons not in map.json keep their Material glyph.
 *
 * Usage (from web/portal):
 *   npm install --no-save lucide-static@0.460.0
 *   node redesign-icons/build.mjs
 */
import { existsSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const portalRoot = join(here, '..');
const lucideDir = join(portalRoot, 'node_modules/lucide-static/icons');
const map = JSON.parse(readFileSync(join(here, 'map.json'), 'utf8'));
const PORTALS = ['platform', 'brand', 'client', 'user'];

// Icons MUI components draw on their own (select arrow, sort arrow,
// pagination, checkboxes, chip delete…).
const MUI_INTERNAL = [
  'ArrowDropDown', 'ArrowDownward', 'KeyboardArrowLeft', 'KeyboardArrowRight',
  'FirstPage', 'LastPage', 'CheckBox', 'CheckBoxOutlineBlank',
  'IndeterminateCheckBox', 'Cancel', 'Close', 'ExpandMore',
];

/** Every @mui/icons-material icon the portals and ivoz-ui import. */
function usedIcons() {
  const found = new Set(MUI_INTERNAL);
  const pattern = /@mui\/icons-material\/([A-Za-z0-9]+)/g;
  const barrel = /import\s*\{([^}]+)\}\s*from\s*'@mui\/icons-material'/g;
  const walk = (dir) => {
    for (const entry of readdirSync(dir)) {
      if (entry === 'node_modules') continue;
      const path = join(dir, entry);
      if (statSync(path).isDirectory()) {
        walk(path);
      } else if (/\.(tsx?|jsx?)$/.test(entry)) {
        const text = readFileSync(path, 'utf8');
        for (const m of text.matchAll(pattern)) found.add(m[1]);
        for (const m of text.matchAll(barrel)) {
          m[1].split(',').forEach((n) => n.trim() && found.add(n.trim().split(/\s+as\s+/)[0]));
        }
      }
    }
  };
  PORTALS.forEach((p) => walk(join(portalRoot, p, 'src')));
  walk(join(portalRoot, 'node_modules/@irontec/ivoz-ui'));

  return [...found].sort();
}

const baseName = (name) => name.replace(/(Rounded|Outlined|Sharp|TwoTone)$/, '');

function dataUri(name) {
  const file = join(lucideDir, `${name}.svg`);
  if (!existsSync(file)) {
    throw new Error(`Lucide icon not found: ${name}`);
  }
  const svg = readFileSync(file, 'utf8')
    .replace(/<!--[\s\S]*?-->/g, '')
    .replace(/\s*class="[^"]*"/, '')
    .replace(/stroke="currentColor"/, 'stroke="black"')
    .replace(/\s+/g, ' ')
    .replace(/> </g, '><')
    .trim();

  // Only the characters a CSS url("…") data URI needs escaped.
  const escaped = svg
    .replace(/%/g, '%25')
    .replace(/#/g, '%23')
    .replace(/"/g, "'")
    .replace(/</g, '%3C')
    .replace(/>/g, '%3E');

  return `url("data:image/svg+xml,${escaped}")`;
}

const lines = [
  '/* Generated by web/portal/redesign-icons/build.mjs. Do not edit by hand. */',
  '/* Icons: Lucide (https://lucide.dev), ISC licence. */',
  '',
];
const selectors = [];

const unmapped = [];
for (const icon of usedIcons()) {
  const lucide = map[icon] ?? map[baseName(icon)];
  if (!lucide) {
    unmapped.push(icon);
    continue;
  }
  const selector = `html.rd svg[data-testid='${icon}Icon']`;
  selectors.push(selector);
  lines.push(`${selector} {\n  --rd-icon: ${dataUri(lucide)};\n}`);
}

lines.push(
  '',
  `:is(${selectors.join(',\n')}) {`,
  '  -webkit-mask: var(--rd-icon) center / 100% 100% no-repeat;',
  '  mask: var(--rd-icon) center / 100% 100% no-repeat;',
  '  background-color: currentColor;',
  '}',
  `:is(${selectors.join(',\n')}) > * {`,
  '  display: none;',
  '}',
  ''
);

const css = lines.join('\n');
if (unmapped.length) {
  console.log('Not mapped (keep the Material glyph):', unmapped.join(', '));
}
for (const portal of PORTALS) {
  const out = join(portalRoot, portal, 'src/components/Redesign/icons.css');
  writeFileSync(out, css);
  console.log('wrote', out, `(${css.length} bytes)`);
}
